function toposhow(cfg,dat)
% toposhow(cfg,dat)
% dat is a column vector of length number of electrodes in cfg
% cfg is generated by topoprepare

if isfield(cfg,'layout'),
    topoplot(cfg,dat);
else
    topoplot(cfg,cfg.X,cfg.Y,dat,cfg.Lbl);
end

